apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-rko2
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-rko2@sha256:8b71beb80cdc744bd3db56675acc19319b0300dedde12d210eff846a4811f9f6
        name: my-python
        resources: {}
status: {}
